-- Migration 004: Create news table (the article queue)
--
-- Default table name is "news" (configurable via settings.db_table). Holds
-- ingested RSS items from feed-grabber until they're tooted; tooted rows are
-- moved to tooted_hashes (just the dedup key) and deleted from here.
--
-- Columns added by later migrations:
--   008 → canonical_url TEXT (normalized URL key for cross-source dedup)
--
-- The hash column needs a non-partial UNIQUE constraint so feed-grabber's
-- upsert(.., { onConflict: "hash", ignoreDuplicates: true }) can resolve
-- the conflict target. Postgres allows multiple NULL values in a UNIQUE
-- column by default, which is fine for legacy / null-hash rows.
--
-- The fts column is a STORED generated tsvector built from data->>'title'
-- and data->>'contentSnippet' in the German text-search config. Used by
-- questionAnswerer.searchArticles via PostgREST's .textSearch("fts", ...,
-- { config: "german" }). Without it, the mention-replier Q&A feature
-- can't find articles for follower questions.

CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hash TEXT UNIQUE,
    data JSONB NOT NULL,
    pub_date TIMESTAMPTZ,
    tooted BOOLEAN NOT NULL DEFAULT FALSE,
    story_id UUID REFERENCES stories(id) ON DELETE SET NULL,
    fts TSVECTOR GENERATED ALWAYS AS (
        to_tsvector(
            'german',
            coalesce(data->>'title', '') || ' ' ||
            coalesce(data->>'contentSnippet', '')
        )
    ) STORED
);

-- feed-tooter selects untooted rows ordered by pub_date desc.
CREATE INDEX IF NOT EXISTS idx_news_tooted_pub_date
    ON news(tooted, pub_date DESC);
-- cleanupOrphanedStoryRefs scans by story_id; threading follows the FK.
CREATE INDEX IF NOT EXISTS idx_news_story_id ON news(story_id);
-- Stale-article cleanup filters by pub_date OR created_at < cutoff.
CREATE INDEX IF NOT EXISTS idx_news_created_at ON news(created_at);
-- Full-text search index for questionAnswerer (German config).
CREATE INDEX IF NOT EXISTS idx_news_fts ON news USING GIN (fts);

COMMENT ON TABLE news IS 'Ingested RSS articles awaiting toot. Cleaned up after tooting (saveHashesAndFinalize) or staleness (cleanupHelpers).';
COMMENT ON COLUMN news.hash IS 'sha256(feedURL)-sha256(title)-sha256(link). Cross-batch dedup key. UNIQUE so upsert(onConflict: hash) can deduplicate races.';
COMMENT ON COLUMN news.data IS 'Raw RSS item from rss-parser, plus _feedKey (added by feed-grabber to retain origin feed identity).';
COMMENT ON COLUMN news.fts IS 'Generated German tsvector over title + contentSnippet. Read via PostgREST .textSearch("fts", q, { config: "german" }) in questionAnswerer.';
